# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  encoders:
    Symfony\Component\Security\Core\User\User: bcrypt
    ProApps\Bundle\PanelBundle\Entity\User:
      algorithm: bcrypt

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory:
      memory:
        users:
          root: { password: $2y$10$yy8iOJ0fgQsA5Kr79.aP1eueVMko7w8qY6Mo9lMLpqdLjcrHDjOHm, roles: 'ROLE_ADMIN' }

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    secured_area:
      pattern:    ^/api
      http_basic: ~
      anonymous: ~
      provider: in_memory
      form_login:
        login_path: /api/login
        check_path: /api/login_check
      logout:
        path:   /api/logout
        target: /api/basic
  access_control:
    - { path: ^/api/weather-root, roles: ROLE_ADMIN }
