<?php

namespace SyntaxError\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SyntaxError\ApiBundle\Entity\ArchiveDayOuttemp;

/**
 * ArchiveDayBarometerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveDayBarometerRepository extends EntityRepository
{
    /**
     * @param \DateTime $dateTime
     * @param $max
     * @return null|ArchiveDayOuttemp
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findMonthRecord(\DateTime $dateTime, $max = true)
    {
        $from = (new \DateTime( $dateTime->format('Y-m-01 00:00:00') ))->getTimestamp()+3600*20;
        $to = (new \DateTime( $dateTime->format('Y-m-t 23:59:59') ))->getTimestamp()+3600*20;
        return $this->getEntityManager()->getRepository("SyntaxErrorApiBundle:ArchiveDayBarometer")->createQueryBuilder('a')
            ->where('a.datetime BETWEEN :from AND :to')
            ->setParameter('from', $from)->setParameter('to', $to)
            ->orderBy('a.max', $max ? 'desc' : 'asc')->setMaxResults(1)->getQuery()->getOneOrNullResult();
    }
}
