<?php

namespace SyntaxError\ApiBundle\Repository;

/**
 * ArchiveDayWindgustRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveDayWindgustRepository extends ArchiveDayRepository
{
}
