<?php

namespace SyntaxError\ApiBundle\Repository;

/**
 * ArchiveDayRainrateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveDayRainrateRepository extends AbstractDayRepository
{
}
