<?php

namespace SyntaxError\ApiBundle\Repository;

/**
 * ArchiveDayBarometerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveDayBarometerRepository extends AbstractDayRepository
{
}
