<?php

namespace SyntaxError\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SyntaxError\ApiBundle\Tools\Uniter;
use SyntaxError\ApiBundle\Entity\Archive;

/**
 * archiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveRepository extends EntityRepository
{
    /**
     * @return null|Archive
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLast()
    {
        return $this->getEntityManager()->getRepository("SyntaxErrorApiBundle:Archive")->createQueryBuilder('a')
            ->orderBy('a.dateTime', 'desc')->setMaxResults(1)->getQuery()->getOneOrNullResult();
    }

    /**
     * @return float
     */
    public function getLastTempTrend()
    {
        $temperatures = $this->getEntityManager()->getRepository("SyntaxErrorApiBundle:Archive")->createQueryBuilder('a')
            ->select('a.outTemp')->orderBy('a.dateTime', 'desc')->setMaxResults(12)->getQuery()->getResult();
        return Uniter::getTrend($temperatures, 'outTemp');
    }

    /**
     * @return float
     */
    public function getLastPressTrend()
    {
        $pressures = $this->getEntityManager()->getRepository("SyntaxErrorApiBundle:Archive")->createQueryBuilder('a')
            ->select('a.pressure')->orderBy('a.dateTime', 'desc')->setMaxResults(12)->getQuery()->getResult();
        return Uniter::getTrend($pressures, 'pressure');
    }

    /**
     * @param \DateTime $dateTime
     * @return array|Archive[]
     */
    public function findByDay(\DateTime $dateTime)
    {
        $from = new \DateTime($dateTime->format("Y-m-d H:i:s"));
        $to = new \DateTime($dateTime->format("Y-m-d H:i:s"));
        $from->setTime(0,0,0);
        $to->setTime(23,59,59);
        return $this->getEntityManager()->getRepository("SyntaxErrorApiBundle:Archive")
            ->createQueryBuilder('a')
            ->where('a.dateTime BETWEEN :from AND :to')
            ->setParameter( 'from', $from->getTimestamp() )
            ->setParameter( 'to', $to->getTimestamp() )
            ->getQuery()->getResult();
    }
}
