<?php

namespace SyntaxError\ApiBundle\Repository;

/**
 * ArchiveDayOuthumidityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveDayOuthumidityRepository extends ArchiveDayRepository
{
}
