syntax_error_api_basic_now:
  path: /basic.{ext}
  defaults: { _controller: SyntaxErrorApiBundle:Basic:now, ext: default }

syntax_error_api_socket:
  path: /websocket
  defaults: { _controller: SyntaxErrorApiBundle:Socket:information, ext: default }

syntax_error_api_wu:
  path: /wu/{type}.{ext}
  defaults: { _controller: SyntaxErrorApiBundle:Basic:wunderground, ext: default }
  requirements: { type: forecast|astronomy }

syntax_error_api_archive_charts:
  path: /{period}-charts/{type}.{ext}
  defaults: { _controller: SyntaxErrorApiBundle:Archive:charts, ext: default }
  requirements: { period: day|month|year }

syntax_error_api_archive_records:
  path: /{period}-records.{ext}
  defaults: { _controller: SyntaxErrorApiBundle:Archive:records, ext: default }
  requirements: { period: day|month|year }

# Redirect
syntax_error_api_home:
  path: /
  defaults: { _controller: FrameworkBundle:Redirect:redirect, route: syntax_error_api_basic_now, permanent: true }
