syntax_error_api_basic_now:
  path: /
  defaults: { _controller: SyntaxErrorApiBundle:Basic:now }

syntax_error_api_socket:
  path: /websocket
  defaults: { _controller: SyntaxErrorApiBundle:Socket:information }

syntax_error_api_wu:
  path: /wu/{type}
  defaults: { _controller: SyntaxErrorApiBundle:Basic:wunderground }
  requirements: { type: forecast|astronomy }

syntax_error_api_day_charts:
  path: /day-charts/{type}
  defaults: { _controller: SyntaxErrorApiBundle:Day:charts }

syntax_error_api_day_records:
  path: /day-records
  defaults: { _controller: SyntaxErrorApiBundle:Day:records }

syntax_error_api_month_charts:
  path: /month-charts/{type}
  defaults: { _controller: SyntaxErrorApiBundle:Month:charts }

syntax_error_api_month_records:
  path: /month-records
  defaults: { _controller: SyntaxErrorApiBundle:Month:records }

syntax_error_api_year_charts:
  path: /year-charts/{type}
  defaults: { _controller: SyntaxErrorApiBundle:Year:charts }

syntax_error_api_year_records:
  path: /year-records
  defaults: { _controller: SyntaxErrorApiBundle:Year:records }
