# Admin
syntax_error_api_admin_login:
  path: /login
  defaults: { _controller: SyntaxErrorApiBundle:Admin:login }

syntax_error_api_admin_login_check:
  path: /login_check

syntax_error_api_admin_logout:
  path: /logout

syntax_error_api_admin_logged:
  path: /weather-root
  defaults: { _controller: SyntaxErrorApiBundle:Admin:logged }

# Api
syntax_error_api_basic_now:
  path: /basic.{ext}
  defaults: { _controller: SyntaxErrorApiBundle:Basic:now, ext: default }

syntax_error_api_wu:
  path: /wu/{type}.{ext}
  defaults: { _controller: SyntaxErrorApiBundle:Basic:wunderground, ext: default }
  requirements: { type: forecast|astronomy|alerts }

syntax_error_api_socket:
  path: /websocket
  defaults: { _controller: SyntaxErrorApiBundle:Info:socket }

syntax_error_api_sentence:
  path: /info.{ext}
  defaults: { _controller: SyntaxErrorApiBundle:Info:sentence, ext: default }

syntax_error_api_archive_records:
  path: /{period}-records.{ext}
  defaults: { _controller: SyntaxErrorApiBundle:Archive:records, ext: default }
  requirements: { period: day|month|year }

syntax_error_api_archive_charts:
  path: /{period}-charts/{type}.{ext}
  defaults: { _controller: SyntaxErrorApiBundle:Archive:charts, ext: default }
  requirements:
    period: day|month|year
    type: outTemp|outHumidity|barometer|windGust|windGustDir|rain|rainRate

# Redirect
syntax_error_api_home:
  path: /
  defaults: { _controller: FrameworkBundle:Redirect:redirect, route: syntax_error_api_basic_now, permanent: true }
