services:
    syntax_error_api.live:
      class: SyntaxError\ApiBundle\Service\LiveService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.info:
      class: SyntaxError\ApiBundle\Service\InfoService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.day:
      class: SyntaxError\ApiBundle\Service\Archive\DayService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.month:
      class: SyntaxError\ApiBundle\Service\Archive\MonthService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.year:
      class: SyntaxError\ApiBundle\Service\Archive\YearService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.wu:
      class: SyntaxError\ApiBundle\Service\Wunderground


    syntax_error_api.admin:
      class: SyntaxError\ApiBundle\Service\Admin
      arguments: [@doctrine.orm.default_entity_manager]

