services:
    syntax_error_api.live:
      class: SyntaxError\ApiBundle\Service\LiveService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.info:
      class: SyntaxError\ApiBundle\Service\InfoService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.day:
      class: SyntaxError\ApiBundle\Service\DayService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.month:
      class: SyntaxError\ApiBundle\Service\MonthService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.year:
      class: SyntaxError\ApiBundle\Service\YearService
      arguments: [@doctrine.orm.default_entity_manager]

    syntax_error_api.wu:
      class: SyntaxError\ApiBundle\Service\Wunderground
