#!/usr/bin/env php
<?php
require __DIR__ . '/../../../vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->setName("Syntax webSocket Server");
$application->setVersion('1.0');
$application->add( new \SyntaxError\SocketBundle\Command\StartCommand() );
$application->add( new \SyntaxError\SocketBundle\Command\StopCommand() );
$application->add( new \SyntaxError\SocketBundle\Command\RestartCommand() );
$application->add( new \SyntaxError\SocketBundle\Command\StatusCommand() );
$application->add( new \SyntaxError\SocketBundle\Command\ConfigCommand() );
$application->add( new \SyntaxError\SocketBundle\Command\ClientsCommand() );
$application->run();
